from __future__ import annotations

import builtins
import csv
import json
from collections.abc import Mapping
from contextlib import ExitStack
from dataclasses import asdict, is_dataclass
import importlib
import inspect
from pathlib import Path
import tempfile
from types import SimpleNamespace
import unittest
from unittest import mock

from slumulation import constants

EXPECTED_BEHAVIORSPACE_COLUMNS = constants.BEHAVIORSPACE_OUTPUT_COLUMNS
EXPECTED_SELECTED_EXPERIMENTS = (
    "Typical Run",
    "Population Growth Rate",
    "Politics and Development ON OFF",
)
EXCLUDED_EXPERIMENT_NAMES = (
    "Urbanization",
    "EconomicGrowth",
    "PrimeLand",
    "No Center Search (Old)",
    "Central Search Off",
)


def _validation_api() -> SimpleNamespace:
    validation = importlib.import_module("slumulation.validation")
    required_exports = (
        "DEFAULT_MESA_BASE_SEED",
        "SeedManifestEntry",
        "SmokeRunResult",
        "MesaValidationOutput",
        "MesaValidationOutputsResult",
        "ComparisonOutputsResult",
        "LoadedBehaviorSpaceTable",
        "ShapeCheckSummary",
        "derive_mesa_seed",
        "build_seed_manifest",
        "write_mesa_smoke_output",
        "write_mesa_validation_outputs",
        "write_comparison_outputs",
        "load_mesa_csv",
        "load_netlogo_behavior_space_table",
        "summarize_table_shape",
    )
    optional_exports = ("ShapeComparisonSummary", "compare_table_shapes")
    missing = [name for name in required_exports if not hasattr(validation, name)]

    if missing:
        raise AssertionError(
            f"slumulation.validation is missing expected public exports: {missing!r}"
        )

    return SimpleNamespace(
        module=validation,
        **{name: getattr(validation, name) for name in required_exports},
        **{
            name: getattr(validation, name)
            for name in optional_exports
            if hasattr(validation, name)
        },
    )


def _baseline_parameters(**overrides) -> dict[str, object]:
    parameters = dict(constants.BASELINE_PARAMETER_VALUES)
    parameters.update(overrides)
    return parameters


def _row_for_step(step: int, **parameter_overrides) -> dict[str, object]:
    parameters = _baseline_parameters(**parameter_overrides)
    return _row_for_parameters(step, run_number=1, parameters=parameters)


def _row_for_parameters(
    step: int,
    *,
    run_number: int = 1,
    parameters: Mapping[str, object] | None = None,
) -> dict[str, object]:
    parameter_values = _baseline_parameters()
    if parameters is not None:
        parameter_values.update(parameters)

    row: dict[str, object] = {"[run number]": run_number}
    row.update(parameter_values)
    row["[step]"] = step
    for metric_index, metric_name in enumerate(constants.SOURCE_EMITTED_METRICS):
        row[metric_name] = metric_index + step / 100
    return row


def _write_simple_csv(
    path: Path,
    rows: list[Mapping[str, object]],
    columns: tuple[str, ...] = EXPECTED_BEHAVIORSPACE_COLUMNS,
) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(columns)
        for row in rows:
            writer.writerow([row.get(column, "") for column in columns])


def _write_netlogo_csv_with_metadata(
    path: Path,
    rows: list[Mapping[str, object]],
    columns: tuple[str, ...] = EXPECTED_BEHAVIORSPACE_COLUMNS,
) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["BehaviorSpace results generated by NetLogo"])
        writer.writerow(["model", "Slumulation"])
        writer.writerow(["experiment", "Typical Run"])
        writer.writerow([])
        writer.writerow(columns)
        for row in rows:
            writer.writerow([row.get(column, "") for column in columns])


def _read_csv_header(path: Path) -> tuple[str, ...]:
    with path.open(newline="", encoding="utf-8") as handle:
        return tuple(next(csv.reader(handle)))


def _read_dict_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _write_tiny_comparison_inputs(
    directory: Path,
    *,
    mesa_rows: list[Mapping[str, object]] | None = None,
    netlogo_rows: list[Mapping[str, object]] | None = None,
) -> tuple[Path, Path]:
    mesa_path = directory / "mesa-typical-run.csv"
    netlogo_path = directory / "netlogo-typical-run.csv"
    rows = [_row_for_step(0), _row_for_step(constants.STEP_MAX)]
    _write_simple_csv(mesa_path, mesa_rows if mesa_rows is not None else rows)
    _write_netlogo_csv_with_metadata(
        netlogo_path,
        netlogo_rows if netlogo_rows is not None else rows,
    )
    return mesa_path, netlogo_path


def _write_tiny_comparison_outputs(api, directory: Path):
    input_dir = directory / "inputs"
    comparison_dir = directory / "comparison"
    input_dir.mkdir()
    mesa_path, netlogo_path = _write_tiny_comparison_inputs(input_dir)
    return api.write_comparison_outputs(
        input_dir,
        comparison_dir,
        experiment_names=("Typical Run",),
        repetitions=1,
        mesa_paths={"Typical Run": mesa_path},
        netlogo_paths={"Typical Run": netlogo_path},
    )


def _call_with_supported_keywords(function, *args, **kwargs):
    signature = inspect.signature(function)
    parameters = signature.parameters
    accepts_kwargs = any(
        parameter.kind == inspect.Parameter.VAR_KEYWORD
        for parameter in parameters.values()
    )
    supported_kwargs = (
        kwargs
        if accepts_kwargs
        else {name: value for name, value in kwargs.items() if name in parameters}
    )
    return function(*args, **supported_kwargs)


def _call_loader(function, path: Path):
    signature = inspect.signature(function)
    if len(signature.parameters) == 0:
        raise AssertionError(f"{function.__name__} must accept a CSV path.")

    first_parameter = next(iter(signature.parameters))
    path_kwargs = {
        "path": path,
        "csv_path": path,
        "file_path": path,
        "table_path": path,
    }
    if first_parameter in path_kwargs:
        return _call_with_supported_keywords(function, **path_kwargs)

    return function(path)


def _derive_seed(api, *, experiment_index=0, parameter_index=0, repetition_index=0):
    return _call_with_supported_keywords(
        api.derive_mesa_seed,
        base_seed=api.DEFAULT_MESA_BASE_SEED,
        experiment_index=experiment_index,
        experiment_order=experiment_index,
        parameter_index=parameter_index,
        parameter_condition_index=parameter_index,
        parameter_combination_index=parameter_index,
        condition_index=parameter_index,
        repetition_index=repetition_index,
        repetition=repetition_index,
        run_index=repetition_index,
        run_number=repetition_index + 1,
        experiment_name=EXPECTED_SELECTED_EXPERIMENTS[experiment_index],
        parameter_label=f"condition-{parameter_index}",
        parameter_values=_baseline_parameters(),
    )


def _build_seed_manifest(api, **overrides):
    experiment = overrides.pop("experiment", None)
    if experiment is None:
        experiment_names = overrides.get(
            "experiment_names",
            overrides.get(
                "selected_experiment_names",
                overrides.get("experiments", ("Typical Run",)),
            ),
        )
        experiment = tuple(experiment_names)[0]

    kwargs = {
        "repetitions": 2,
        "base_seed": api.DEFAULT_MESA_BASE_SEED,
    }
    kwargs.update(overrides)
    return _call_with_supported_keywords(api.build_seed_manifest, experiment, **kwargs)


def _columns(table) -> tuple[str, ...]:
    value = _field(table, "columns", "fieldnames", "field_names", "header")
    return tuple(value)


def _rows(table) -> list[object]:
    return list(_field(table, "rows", "records", "data_rows", "data"))


def _field(record, *names):
    if isinstance(record, Mapping):
        for name in names:
            if name in record:
                return record[name]

    for name in names:
        if hasattr(record, name):
            return getattr(record, name)

    raise AssertionError(f"Missing expected field from {record!r}: {names!r}")


def _row_value(row, column: str):
    if isinstance(row, Mapping):
        return row[column]
    return getattr(row, column)


def _table_from_csv(api, tmp_path: Path, rows: list[Mapping[str, object]], columns):
    csv_path = tmp_path / "table.csv"
    _write_simple_csv(csv_path, rows, columns)
    return _call_loader(api.load_mesa_csv, csv_path)


def _table_from_netlogo_csv(
    api,
    tmp_path: Path,
    rows: list[Mapping[str, object]],
    columns: tuple[str, ...],
):
    csv_path = tmp_path / "netlogo-table.csv"
    _write_netlogo_csv_with_metadata(csv_path, rows, columns)
    return _call_loader(api.load_netlogo_behavior_space_table, csv_path)


def _summarize_shape(api, table, **overrides):
    kwargs = {
        "table": table,
        "loaded_table": table,
        "behavior_space_table": table,
        "expected_columns": EXPECTED_BEHAVIORSPACE_COLUMNS,
        "required_columns": EXPECTED_BEHAVIORSPACE_COLUMNS,
        "expected_metrics": constants.PRIMARY_VALIDATION_METRICS,
        "required_metrics": constants.PRIMARY_VALIDATION_METRICS,
        "primary_metrics": constants.PRIMARY_VALIDATION_METRICS,
        "expected_step_min": 0,
        "expected_step_max": 50,
        "step_min": 0,
        "step_max": 50,
        "expected_steps": tuple(range(51)),
        "expected_row_count": 51,
        "expected_rows": 51,
        "expected_rows_per_run": 51,
        "rows_per_run": 51,
        "expected_run_count": 1,
        "expected_runs": 1,
        "expected_parameter_conditions": (_baseline_parameters(),),
        "expected_parameter_combinations": (_baseline_parameters(),),
        "parameter_conditions": (_baseline_parameters(),),
    }
    kwargs.update(overrides)

    signature = inspect.signature(api.summarize_table_shape)
    if any(name in signature.parameters for name in ("table", "loaded_table")):
        return _call_with_supported_keywords(api.summarize_table_shape, **kwargs)

    return _call_with_supported_keywords(
        api.summarize_table_shape,
        table,
        **{name: value for name, value in kwargs.items() if name not in {"table"}},
    )


def _summary_text(summary) -> str:
    if is_dataclass(summary):
        return repr(asdict(summary))
    if isinstance(summary, Mapping):
        return repr(dict(summary))
    return repr(vars(summary) if hasattr(summary, "__dict__") else summary)


def _summary_indicates_problem(summary) -> bool:
    for name in ("is_valid", "valid", "ok", "passed", "shape_matches"):
        if hasattr(summary, name) and getattr(summary, name) is False:
            return True
        if isinstance(summary, Mapping) and summary.get(name) is False:
            return True

    for name in (
        "errors",
        "failures",
        "issues",
        "missing_columns",
        "extra_columns",
        "missing_metrics",
        "extra_steps",
        "unexpected_steps",
        "parameter_mismatches",
        "unexpected_parameter_conditions",
    ):
        try:
            value = _field(summary, name)
        except AssertionError:
            continue
        if value:
            return True

    return False


class SlumulationValidationTests(unittest.TestCase):
    def test_validation_module_exports_expected_contract(self) -> None:
        api = _validation_api()

        for name in (
            "SeedManifestEntry",
            "SmokeRunResult",
            "MesaValidationOutput",
            "MesaValidationOutputsResult",
            "ComparisonOutputsResult",
            "LoadedBehaviorSpaceTable",
            "ShapeCheckSummary",
        ):
            with self.subTest(name=name):
                self.assertTrue(is_dataclass(getattr(api, name)))

        if hasattr(api, "ShapeComparisonSummary"):
            self.assertTrue(is_dataclass(api.ShapeComparisonSummary))

        for name in (
            "write_mesa_validation_outputs",
            "write_comparison_outputs",
        ):
            with self.subTest(name=name):
                self.assertTrue(callable(getattr(api, name)))
                self.assertIn(name, getattr(api.module, "__all__", ()))

    def test_validation_outputs_use_injected_runner_writer_and_raw_schema(
        self,
    ) -> None:
        api = _validation_api()
        selected_experiments = ("Typical Run", "Population Growth Rate")
        run_calls: list[dict[str, object]] = []
        write_calls: list[tuple[Path, tuple[Mapping[str, object], ...]]] = []

        def run_rows_stub(experiment, **kwargs):
            parameter_combination = kwargs["parameter_combination"]
            run_calls.append(
                {
                    "experiment": experiment.name,
                    "run_number": kwargs["run_number"],
                    "seed": kwargs["seed"],
                    "max_steps": kwargs.get("max_steps"),
                }
            )
            return (
                _row_for_parameters(
                    0,
                    run_number=kwargs["run_number"],
                    parameters=dict(parameter_combination.values),
                ),
            )

        def write_rows_stub(path, rows):
            materialized_rows = tuple(rows)
            for row in materialized_rows:
                self.assertEqual(set(row), set(EXPECTED_BEHAVIORSPACE_COLUMNS))
                self.assertNotIn("seed", row)
            write_calls.append((Path(path), materialized_rows))
            _write_simple_csv(Path(path), list(materialized_rows))

        with tempfile.TemporaryDirectory() as directory:
            output_dir = Path(directory) / "mesa"
            result = api.write_mesa_validation_outputs(
                output_dir,
                experiment_names=selected_experiments,
                repetitions=1,
                write_manifest=False,
                run_rows_fn=run_rows_stub,
                write_rows_fn=write_rows_stub,
            )

            csv_paths = sorted(output_dir.glob("*.csv"))
            self.assertEqual(len(csv_paths), len(selected_experiments))
            for csv_path in csv_paths:
                with self.subTest(csv_path=csv_path.name):
                    header = _read_csv_header(csv_path)
                    self.assertEqual(header, EXPECTED_BEHAVIORSPACE_COLUMNS)
                    self.assertEqual(len(header), constants.RAW_OUTPUT_COLUMNS)
                    self.assertNotIn("seed", header)

        self.assertEqual(
            [output.experiment_name for output in result.outputs],
            list(selected_experiments),
        )
        self.assertEqual(len(write_calls), len(selected_experiments))
        self.assertEqual(len(run_calls), 4)
        self.assertEqual(
            [call["experiment"] for call in run_calls],
            [
                "Typical Run",
                "Population Growth Rate",
                "Population Growth Rate",
                "Population Growth Rate",
            ],
        )

    def test_validation_outputs_seed_sidecar_records_all_runs_without_raw_seed(
        self,
    ) -> None:
        api = _validation_api()

        def run_rows_stub(experiment, **kwargs):
            parameter_combination = kwargs["parameter_combination"]
            return (
                _row_for_parameters(
                    0,
                    run_number=kwargs["run_number"],
                    parameters=dict(parameter_combination.values),
                ),
            )

        def write_rows_stub(path, rows):
            _write_simple_csv(Path(path), list(rows))

        with tempfile.TemporaryDirectory() as directory:
            output_dir = Path(directory) / "mesa"
            result = api.write_mesa_validation_outputs(
                output_dir,
                experiment_names=("Population Growth Rate",),
                repetitions=2,
                run_rows_fn=run_rows_stub,
                write_rows_fn=write_rows_stub,
            )

            self.assertIsNotNone(result.manifest_path)
            with Path(result.manifest_path).open(encoding="utf-8") as handle:
                payload = json.load(handle)

            entries = payload["entries"]
            output = result.outputs[0]
            raw_header = _read_csv_header(output.output_path)
            raw_rows = _read_dict_csv(output.output_path)

        self.assertEqual(len(entries), 6)
        self.assertEqual(len(entries), len(result.seed_manifest))
        self.assertEqual(len(entries), output.run_count)
        self.assertEqual([entry["run_number"] for entry in entries], list(range(1, 7)))
        self.assertTrue(all(isinstance(entry["seed"], int) for entry in entries))
        self.assertEqual(raw_header, EXPECTED_BEHAVIORSPACE_COLUMNS)
        self.assertEqual(len(raw_header), constants.RAW_OUTPUT_COLUMNS)
        self.assertNotIn("seed", raw_header)
        self.assertTrue(all("seed" not in row for row in raw_rows))

    def test_validation_outputs_reject_name_alias_conflicts_and_bad_repetitions(
        self,
    ) -> None:
        api = _validation_api()

        def fail_if_called(*args, **kwargs):
            raise AssertionError("validation should fail before running rows")

        cases = (
            {
                "experiment_names": ("Typical Run",),
                "selected_experiment_names": ("Population Growth Rate",),
                "repetitions": 1,
            },
            {"experiment_names": ("Typical Run",), "repetitions": 0},
            {"experiment_names": ("Typical Run",), "repetition_count": 0},
            {
                "experiment_names": ("Typical Run",),
                "repetitions": 2,
                "repetition_count": 3,
            },
        )

        with tempfile.TemporaryDirectory() as directory:
            output_dir = Path(directory) / "mesa"
            for kwargs in cases:
                with self.subTest(kwargs=kwargs):
                    with self.assertRaises(ValueError):
                        api.write_mesa_validation_outputs(
                            output_dir,
                            run_rows_fn=fail_if_called,
                            write_rows_fn=fail_if_called,
                            **kwargs,
                        )

    def test_comparison_outputs_load_tiny_inputs_and_separate_metric_groups(
        self,
    ) -> None:
        api = _validation_api()

        with tempfile.TemporaryDirectory() as directory:
            result = _write_tiny_comparison_outputs(api, Path(directory))
            final_step_rows = _read_dict_csv(result.final_step_path)
            trajectory_rows = _read_dict_csv(result.trajectories_path)
            supporting_raw_rows = _read_dict_csv(result.supporting_trajectories_path)

        self.assertEqual(result.experiments, ("Typical Run",))
        self.assertEqual(
            {row["metric"] for row in final_step_rows},
            set(constants.PRIMARY_VALIDATION_METRICS),
        )
        self.assertLessEqual(
            {row["metric"] for row in trajectory_rows},
            set(constants.PRIMARY_VALIDATION_METRICS),
        )
        self.assertTrue(final_step_rows)
        self.assertTrue(trajectory_rows)
        self.assertEqual(
            {row["metric"] for row in supporting_raw_rows},
            set(constants.SUPPORTING_METRIC_NAMES + constants.RAW_ONLY_METRIC_NAMES),
        )
        self.assertTrue(
            set(constants.PRIMARY_VALIDATION_METRICS).isdisjoint(
                {row["metric"] for row in supporting_raw_rows}
            )
        )

    def test_supporting_raw_summary_keeps_largest_slum_raw_only(self) -> None:
        api = _validation_api()

        with tempfile.TemporaryDirectory() as directory:
            result = _write_tiny_comparison_outputs(api, Path(directory))
            final_step_rows = _read_dict_csv(result.final_step_path)
            trajectory_rows = _read_dict_csv(result.trajectories_path)
            supporting_raw_rows = _read_dict_csv(result.supporting_trajectories_path)

        self.assertNotIn(
            "largest-slum",
            {row["metric"] for row in final_step_rows},
        )
        self.assertNotIn(
            "largest-slum",
            {row["metric"] for row in trajectory_rows},
        )
        largest_slum_rows = [
            row for row in supporting_raw_rows if row["metric"] == "largest-slum"
        ]
        self.assertTrue(largest_slum_rows)
        self.assertEqual(
            {row["metric_category"] for row in largest_slum_rows},
            {"raw_only"},
        )

    def test_comparison_output_headers_have_deltas_without_claim_labels(
        self,
    ) -> None:
        api = _validation_api()

        with tempfile.TemporaryDirectory() as directory:
            result = _write_tiny_comparison_outputs(api, Path(directory))
            final_header = _read_csv_header(result.final_step_path)
            trajectory_header = _read_csv_header(result.trajectories_path)
            supporting_raw_header = _read_csv_header(
                result.supporting_trajectories_path
            )

        for header in (final_header, trajectory_header, supporting_raw_header):
            with self.subTest(header=header):
                self.assertIn("mean_difference_mesa_minus_netlogo", header)
                self.assertIn("absolute_mean_difference", header)
                self.assertIn("relative_mean_difference", header)

        disallowed_claim_fields = {
            "pass",
            "passed",
            "fail",
            "failed",
            "matched",
            "mismatched",
            "status",
            "classification",
        }
        for header in (final_header, trajectory_header, supporting_raw_header):
            with self.subTest(header=header):
                self.assertFalse(disallowed_claim_fields.intersection(header))

    def test_parameter_normalization_aligns_boolean_and_numeric_conditions(
        self,
    ) -> None:
        api = _validation_api()
        experiment = constants.POLITICS_DEVELOPMENT_ON_OFF_EXPERIMENT
        expected_conditions = tuple(
            parameter_combination.values
            for parameter_combination in experiment.parameter_combinations
        )
        mesa_rows: list[Mapping[str, object]] = []
        netlogo_rows: list[Mapping[str, object]] = []

        for run_number, parameter_combination in enumerate(
            experiment.parameter_combinations,
            start=1,
        ):
            mesa_parameters = dict(parameter_combination.values)
            mesa_parameters["popgrowthrate"] = "3.0"
            mesa_parameters["SimulationRuntime"] = "50.0"

            netlogo_parameters: dict[str, object] = {}
            for name, value in parameter_combination.values:
                if isinstance(value, bool):
                    netlogo_parameters[name] = str(value).lower()
                elif name == "popgrowthrate":
                    netlogo_parameters[name] = "3"
                elif name == "SimulationRuntime":
                    netlogo_parameters[name] = "50"
                else:
                    netlogo_parameters[name] = value

            mesa_rows.append(
                _row_for_parameters(
                    0,
                    run_number=run_number,
                    parameters=mesa_parameters,
                )
            )
            netlogo_rows.append(
                _row_for_parameters(
                    0,
                    run_number=run_number,
                    parameters=netlogo_parameters,
                )
            )

        with tempfile.TemporaryDirectory() as directory:
            tmp_path = Path(directory)
            mesa_path = tmp_path / "mesa-bools.csv"
            netlogo_path = tmp_path / "netlogo-bools.csv"
            _write_simple_csv(mesa_path, mesa_rows)
            _write_netlogo_csv_with_metadata(netlogo_path, netlogo_rows)
            mesa_table = _call_loader(api.load_mesa_csv, mesa_path)
            netlogo_table = _call_loader(
                api.load_netlogo_behavior_space_table,
                netlogo_path,
            )

            mesa_summary = api.summarize_table_shape(
                mesa_table,
                expected_parameter_conditions=expected_conditions,
            )
            netlogo_summary = api.summarize_table_shape(
                netlogo_table,
                expected_parameter_conditions=expected_conditions,
            )

        for summary in (mesa_summary, netlogo_summary):
            with self.subTest(source=_field(summary, "source")):
                self.assertEqual(_field(summary, "parameter_condition_count"), 4)
                self.assertEqual(_field(summary, "missing_parameter_conditions"), ())
                self.assertEqual(
                    _field(summary, "unexpected_parameter_conditions"),
                    (),
                )

    def test_netlogo_loader_skips_behaviorspace_metadata_and_recovers_data_columns(
        self,
    ) -> None:
        api = _validation_api()
        rows = [_row_for_step(0), _row_for_step(1)]

        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "netlogo-table.csv"
            _write_netlogo_csv_with_metadata(path, rows)

            table = _call_loader(api.load_netlogo_behavior_space_table, path)

        self.assertEqual(_columns(table), EXPECTED_BEHAVIORSPACE_COLUMNS)
        self.assertEqual(len(_columns(table)), constants.RAW_OUTPUT_COLUMNS)
        self.assertEqual(len(_rows(table)), 2)
        self.assertEqual(str(_row_value(_rows(table)[0], "[step]")), "0")

    def test_mesa_loader_reads_simple_header_plus_data_csv(self) -> None:
        api = _validation_api()
        rows = [_row_for_step(0), _row_for_step(1)]

        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "mesa-table.csv"
            _write_simple_csv(path, rows)

            table = _call_loader(api.load_mesa_csv, path)

        self.assertEqual(_columns(table), EXPECTED_BEHAVIORSPACE_COLUMNS)
        self.assertEqual(len(_rows(table)), 2)
        self.assertEqual(str(_row_value(_rows(table)[1], "[step]")), "1")

    def test_shape_summary_accepts_clean_single_run_smoke_shape(self) -> None:
        api = _validation_api()
        rows = [_row_for_step(step) for step in range(51)]

        with tempfile.TemporaryDirectory() as directory:
            table = _table_from_csv(
                api, Path(directory), rows, EXPECTED_BEHAVIORSPACE_COLUMNS
            )
            summary = _summarize_shape(api, table)

        self.assertFalse(
            _summary_indicates_problem(summary),
            f"Expected clean smoke shape, got {summary!r}",
        )

    def test_shape_summary_catches_missing_column(self) -> None:
        api = _validation_api()
        columns = tuple(
            column
            for column in EXPECTED_BEHAVIORSPACE_COLUMNS
            if column != "largest-slum"
        )
        rows = [_row_for_step(step) for step in range(51)]

        with tempfile.TemporaryDirectory() as directory:
            table = _table_from_netlogo_csv(api, Path(directory), rows, columns)
            summary = _summarize_shape(api, table)

        self.assertTrue(_summary_indicates_problem(summary), _summary_text(summary))
        self.assertIn("largest-slum", _summary_text(summary))

    def test_shape_summary_catches_extra_step_51(self) -> None:
        api = _validation_api()
        rows = [_row_for_step(step) for step in range(52)]

        with tempfile.TemporaryDirectory() as directory:
            table = _table_from_csv(
                api, Path(directory), rows, EXPECTED_BEHAVIORSPACE_COLUMNS
            )
            summary = _summarize_shape(
                api,
                table,
                expected_row_count=51,
                expected_rows=51,
            )

        self.assertEqual(_field(summary, "row_count"), 52)
        self.assertEqual(_field(summary, "step_max"), 51)
        self.assertIn(51, _field(summary, "step_values"))

    def test_shape_summary_catches_wrong_row_count(self) -> None:
        api = _validation_api()
        rows = [_row_for_step(step) for step in range(50)]

        with tempfile.TemporaryDirectory() as directory:
            table = _table_from_csv(
                api, Path(directory), rows, EXPECTED_BEHAVIORSPACE_COLUMNS
            )
            summary = _summarize_shape(api, table)

        self.assertEqual(_field(summary, "row_count"), 50)
        self.assertEqual(_field(summary, "step_max"), 49)
        self.assertNotEqual(_field(summary, "row_count"), 51)

    def test_shape_summary_catches_missing_metric_even_when_column_count_matches(
        self,
    ) -> None:
        api = _validation_api()
        columns = tuple(
            "unexpected-metric" if column == "slumpoppercent" else column
            for column in EXPECTED_BEHAVIORSPACE_COLUMNS
        )
        rows = [_row_for_step(step) for step in range(51)]

        with tempfile.TemporaryDirectory() as directory:
            table = _table_from_netlogo_csv(api, Path(directory), rows, columns)
            summary = _summarize_shape(api, table)

        self.assertTrue(_summary_indicates_problem(summary), _summary_text(summary))
        self.assertIn("slumpoppercent", _summary_text(summary))

    def test_shape_summary_catches_selected_parameter_condition_mismatch(
        self,
    ) -> None:
        api = _validation_api()
        rows = [_row_for_step(step, popgrowthrate=4) for step in range(51)]

        with tempfile.TemporaryDirectory() as directory:
            table = _table_from_csv(
                api, Path(directory), rows, EXPECTED_BEHAVIORSPACE_COLUMNS
            )
            summary = _summarize_shape(api, table)

        self.assertTrue(_summary_indicates_problem(summary), _summary_text(summary))
        self.assertIn("popgrowthrate", _summary_text(summary))

    def test_seed_derivation_is_deterministic_and_avoids_python_hash(self) -> None:
        api = _validation_api()

        with mock.patch.object(
            builtins,
            "hash",
            side_effect=AssertionError("derive_mesa_seed must not call hash()"),
        ):
            first_seed = _derive_seed(
                api, experiment_index=1, parameter_index=2, repetition_index=3
            )
            repeated_seed = _derive_seed(
                api, experiment_index=1, parameter_index=2, repetition_index=3
            )
            next_repetition_seed = _derive_seed(
                api, experiment_index=1, parameter_index=2, repetition_index=4
            )

        self.assertIsInstance(first_seed, int)
        self.assertEqual(first_seed, repeated_seed)
        self.assertNotEqual(first_seed, next_repetition_seed)

    def test_seed_manifest_records_repetition_seeds_without_expanding_raw_schema(
        self,
    ) -> None:
        api = _validation_api()

        manifest = list(_build_seed_manifest(api, repetitions=2, repetition_count=2))

        self.assertEqual(len(manifest), 2)
        for entry in manifest:
            with self.subTest(entry=entry):
                self.assertIsInstance(_field(entry, "seed", "mesa_seed"), int)
                self.assertIsNotNone(_field(entry, "experiment", "experiment_name"))
                self.assertIsNotNone(
                    _field(entry, "run_number", "mesa_run_number", "repetition")
                )
                self.assertNotIn("seed", EXPECTED_BEHAVIORSPACE_COLUMNS)

    def test_smoke_output_helper_uses_runner_and_writer_injection_boundaries(
        self,
    ) -> None:
        api = _validation_api()
        runner_module = importlib.import_module("slumulation.runner")
        calls: list[tuple[str, object]] = []
        sentinel_rows = (
            _row_for_step(0),
            _row_for_step(1),
        )

        def run_rows_stub(*args, **kwargs):
            calls.append(("run", kwargs))
            self.assertIn("seed", kwargs)
            return sentinel_rows

        def write_rows_stub(path, rows):
            materialized_rows = tuple(rows)
            calls.append(("write", (Path(path), materialized_rows)))
            self.assertEqual(materialized_rows, sentinel_rows)

        with tempfile.TemporaryDirectory() as directory:
            output_path = Path(directory) / "mesa-smoke.csv"
            with ExitStack() as stack:
                stack.enter_context(
                    mock.patch.object(
                        runner_module,
                        "run_behavior_space_rows",
                        side_effect=run_rows_stub,
                    )
                )
                stack.enter_context(
                    mock.patch.object(
                        runner_module,
                        "write_behavior_space_rows",
                        side_effect=write_rows_stub,
                    )
                )
                if hasattr(api.module, "run_behavior_space_rows"):
                    stack.enter_context(
                        mock.patch.object(
                            api.module,
                            "run_behavior_space_rows",
                            side_effect=run_rows_stub,
                        )
                    )
                if hasattr(api.module, "write_behavior_space_rows"):
                    stack.enter_context(
                        mock.patch.object(
                            api.module,
                            "write_behavior_space_rows",
                            side_effect=write_rows_stub,
                        )
                    )

                _call_with_supported_keywords(
                    api.write_mesa_smoke_output,
                    output_path=output_path,
                    path=output_path,
                    csv_path=output_path,
                    experiment_name="Typical Run",
                    experiment_names=("Typical Run",),
                    selected_experiment_names=("Typical Run",),
                    repetitions=1,
                    repetition_count=1,
                    base_seed=api.DEFAULT_MESA_BASE_SEED,
                    run_rows_fn=run_rows_stub,
                    run_behavior_space_rows_fn=run_rows_stub,
                    row_runner=run_rows_stub,
                    write_rows_fn=write_rows_stub,
                    write_behavior_space_rows_fn=write_rows_stub,
                    writer=write_rows_stub,
                )

        self.assertEqual([call[0] for call in calls], ["run", "write"])

    def test_unknown_and_excluded_experiments_remain_rejected(self) -> None:
        api = _validation_api()

        for experiment_name in (*EXCLUDED_EXPERIMENT_NAMES, "Not A Real Experiment"):
            with self.subTest(experiment_name=experiment_name):
                with self.assertRaises(ValueError):
                    _build_seed_manifest(
                        api,
                        experiment_names=(experiment_name,),
                        selected_experiment_names=(experiment_name,),
                        experiments=(experiment_name,),
                        repetitions=1,
                        repetition_count=1,
                    )


if __name__ == "__main__":
    unittest.main()
